server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/region/**
            - Path=/customer/**
            - Path=/customer-image/**
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoice/**
            - Path=/invoice/**
            - Path=/invoice-image/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/category/**
            - Path=/product/**
            - Path=/product-image/**
